/**
 * Guest Demo Data
 * Used when a user logs in as guest (no access_token).
 * Provides realistic triage records for both ASHA and DMO dashboards.
 */

const now = new Date()
const daysAgo = (n) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString()
const hoursAgo = (n) => new Date(now.getTime() - n * 60 * 60 * 1000).toISOString()

export const GUEST_TRIAGE_RECORDS = [
  {
    id: 'demo-001',
    patient_id: 'p-001',
    patient_name: 'Meera Shinde',
    age: 28,
    gender: 'Female',
    district: 'Pune',
    severity: 'red',
    health_condition: 'High fever, convulsions',
    brief: 'High fever 104°F with convulsions since morning',
    created_at: hoursAgo(2),
    reviewed: false,
    sickle_cell_risk: false,
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    id: 'demo-002',
    patient_id: 'p-002',
    patient_name: 'Raju Pawar',
    age: 45,
    gender: 'Male',
    district: 'Pune',
    severity: 'red',
    health_condition: 'Chest pain, breathlessness',
    brief: 'Severe chest pain radiating to left arm, sweating',
    created_at: hoursAgo(5),
    reviewed: false,
    sickle_cell_risk: false,
    latitude: 18.5314,
    longitude: 73.8446,
  },
  {
    id: 'demo-003',
    patient_id: 'p-003',
    patient_name: 'Sunita Kamble',
    age: 32,
    gender: 'Female',
    district: 'Pune',
    severity: 'yellow',
    health_condition: 'Anaemia, fatigue',
    brief: 'Pale skin, tired, Hb 7.2 — possible sickle cell',
    created_at: hoursAgo(8),
    reviewed: false,
    sickle_cell_risk: true,
    latitude: 18.5124,
    longitude: 73.8234,
  },
  {
    id: 'demo-004',
    patient_id: 'p-004',
    patient_name: 'Anita More',
    age: 24,
    gender: 'Female',
    district: 'Pune',
    severity: 'yellow',
    health_condition: 'Ante-natal care visit',
    brief: '7 months pregnant, BP 145/95, mild oedema',
    created_at: hoursAgo(12),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5090,
    longitude: 73.8610,
  },
  {
    id: 'demo-005',
    patient_id: 'p-005',
    patient_name: 'Kishore Jadhav',
    age: 58,
    gender: 'Male',
    district: 'Pune',
    severity: 'yellow',
    health_condition: 'Diabetes, foot ulcer',
    brief: 'Poorly controlled diabetes, infected ulcer on left foot',
    created_at: daysAgo(1),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5360,
    longitude: 73.8715,
  },
  {
    id: 'demo-006',
    patient_id: 'p-006',
    patient_name: 'Lakshmi Bhosale',
    age: 9,
    gender: 'Female',
    district: 'Khordha',
    severity: 'red',
    health_condition: 'Acute diarrhoea, dehydration',
    brief: 'Severe dehydration, sunken eyes, 8+ loose stools per day',
    created_at: daysAgo(1),
    reviewed: false,
    sickle_cell_risk: false,
    latitude: 20.1609,
    longitude: 85.7008,
  },
  {
    id: 'demo-007',
    patient_id: 'p-007',
    patient_name: 'Prakash Nair',
    age: 67,
    gender: 'Male',
    district: 'Cuttack',
    severity: 'green',
    health_condition: 'Hypertension follow-up',
    brief: 'BP 138/88 — stable on medication, monthly review',
    created_at: daysAgo(2),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 20.4625,
    longitude: 85.8828,
  },
  {
    id: 'demo-008',
    patient_id: 'p-008',
    patient_name: 'Kavya Reddy',
    age: 19,
    gender: 'Female',
    district: 'Ganjam',
    severity: 'green',
    health_condition: 'Immunisation — DPT booster',
    brief: 'Routine immunisation, no adverse reactions',
    created_at: daysAgo(2),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 19.3869,
    longitude: 84.8660,
  },
  {
    id: 'demo-009',
    patient_id: 'p-009',
    patient_name: 'Ramesh Yadav',
    age: 41,
    gender: 'Male',
    district: 'Cuttack',
    severity: 'yellow',
    health_condition: 'TB follow-up',
    brief: 'DOTS day 45 — mild weight loss, cough persisting',
    created_at: daysAgo(3),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 20.4744,
    longitude: 85.8820,
  },
  {
    id: 'demo-010',
    patient_id: 'p-010',
    patient_name: 'Shalini Patil',
    age: 35,
    gender: 'Female',
    district: 'Pune',
    severity: 'green',
    health_condition: 'Post-natal visit',
    brief: 'Mother and infant healthy, breastfeeding well',
    created_at: daysAgo(3),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5100,
    longitude: 73.8450,
  },
  {
    id: 'demo-011',
    patient_id: 'p-011',
    patient_name: 'Gopal Deshmukh',
    age: 72,
    gender: 'Male',
    district: 'Khordha',
    severity: 'red',
    health_condition: 'Stroke symptoms',
    brief: 'Sudden speech difficulty and facial droop since 6 AM',
    created_at: daysAgo(4),
    reviewed: false,
    sickle_cell_risk: false,
    latitude: 20.1740,
    longitude: 85.7200,
  },
  {
    id: 'demo-012',
    patient_id: 'p-012',
    patient_name: 'Rohini Sawant',
    age: 26,
    gender: 'Female',
    district: 'Ganjam',
    severity: 'green',
    health_condition: 'Family planning counselling',
    brief: 'IUD insertion completed successfully, no complications',
    created_at: daysAgo(4),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 19.3750,
    longitude: 84.8550,
  },
  {
    id: 'demo-013',
    patient_id: 'p-013',
    patient_name: 'Vijay Kumar',
    age: 53,
    gender: 'Male',
    district: 'Pune',
    severity: 'yellow',
    health_condition: 'Malaria — P. vivax confirmed',
    brief: 'RDT positive for P.vivax, fever cycles every 48h',
    created_at: daysAgo(5),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5220,
    longitude: 73.8600,
  },
  {
    id: 'demo-014',
    patient_id: 'p-014',
    patient_name: 'Priya Kulkarni',
    age: 14,
    gender: 'Female',
    district: 'Pune',
    severity: 'green',
    health_condition: 'Nutritional assessment',
    brief: 'Mid-upper arm circumference normal, growth on track',
    created_at: daysAgo(5),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5050,
    longitude: 73.8510,
  },
  {
    id: 'demo-015',
    patient_id: 'p-015',
    patient_name: 'Manoj Tiwari',
    age: 38,
    gender: 'Male',
    district: 'Cuttack',
    severity: 'yellow',
    health_condition: 'Snake bite — non-venomous',
    brief: 'Local swelling at bite site, given anti-histamine',
    created_at: daysAgo(6),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 20.4680,
    longitude: 85.8900,
  },
  {
    id: 'demo-016',
    patient_id: 'p-016',
    patient_name: 'Deepa Nair',
    age: 29,
    gender: 'Female',
    district: 'Ganjam',
    severity: 'green',
    health_condition: 'ANC — 1st trimester',
    brief: '10 weeks pregnant, IFA + folic acid started',
    created_at: daysAgo(6),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 19.3920,
    longitude: 84.8480,
  },
  {
    id: 'demo-017',
    patient_id: 'p-017',
    patient_name: 'Suresh Gawde',
    age: 62,
    gender: 'Male',
    district: 'Khordha',
    severity: 'red',
    health_condition: 'Respiratory distress',
    brief: 'Oxygen saturation 84%, bilateral crackles — urgent referral needed',
    created_at: daysAgo(7),
    reviewed: false,
    sickle_cell_risk: false,
    latitude: 20.1500,
    longitude: 85.7100,
  },
  {
    id: 'demo-018',
    patient_id: 'p-018',
    patient_name: 'Nita Bhade',
    age: 44,
    gender: 'Female',
    district: 'Pune',
    severity: 'green',
    health_condition: 'Cervical cancer screening',
    brief: 'VIA negative, no lesions detected',
    created_at: daysAgo(8),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 18.5180,
    longitude: 73.8530,
  },
  {
    id: 'demo-019',
    patient_id: 'p-019',
    patient_name: 'Arjun Singh',
    age: 5,
    gender: 'Male',
    district: 'Cuttack',
    severity: 'yellow',
    health_condition: 'Moderate acute malnutrition',
    brief: 'WAZ -2.5, MUAC 11.8 cm — enrolled in NRC',
    created_at: daysAgo(9),
    reviewed: false,
    sickle_cell_risk: true,
    latitude: 20.4800,
    longitude: 85.8660,
  },
  {
    id: 'demo-020',
    patient_id: 'p-020',
    patient_name: 'Rekha Mishra',
    age: 33,
    gender: 'Female',
    district: 'Ganjam',
    severity: 'red',
    health_condition: 'Post-partum haemorrhage',
    brief: 'Excessive bleeding 4h after delivery, urgent hospital referral',
    created_at: daysAgo(10),
    reviewed: true,
    sickle_cell_risk: false,
    latitude: 19.3800,
    longitude: 84.8700,
  },
]

/**
 * Groups the records into patient objects for the ASHA dashboard format.
 */
export function buildAshaPatients(records) {
  const grouped = new Map()
  for (const r of records) {
    const k = `${(r.patient_name || '').toLowerCase()}_${r.age}_${r.district}`
    if (!grouped.has(k)) {
      grouped.set(k, {
        id: r.patient_id || k,
        name: r.patient_name,
        age: r.age,
        gender: r.gender,
        district: r.district,
        triage_records: [],
      })
    }
    grouped.get(k).triage_records.push({
      id: r.id,
      severity: r.severity,
      brief: r.brief,
      created_at: r.created_at,
    })
  }
  return Array.from(grouped.values()).map((p) => {
    p.triage_records.sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
    p.latestSeverity = p.triage_records[0]?.severity || null
    return p
  })
}
